### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by Meeswh** [jasonrwang/oecd_insights#18]
To-Do

[ ]- Philip: Have a great day
[ ]- Mees: Make fork / limitations / further research
[ ]- Jason: Create influence diagram + help Siemon
[ ] - Siemon: Explain Philip figures + code to words + convert to 1 document

**Comment by jasonrwang** [comment]
I'll also help merge Philip's work in `Model diagnostics test.docx`.

**Comment by SKeij** [comment]
- [ ] Philip: Read the report and improve
- [ ] Jason: Read the report and improve
- [ ] Mees: Read the report and improve
- [ ] Jason: look at the GDP output of the model
- [ ] Siemon: Clean up the github
